[metadata]
name = ngs_tools
version = 0.0.1
author = Ivankina A. Elena
description = Tools for checking nucleic acid and consume it
long_description = file: README.md
long_description_content_type = text/markdown

[options]
packages = find_namespace:
python_requires = ~=3.12

[options.extras_require]
dev =
    black==25.9.0
    flake8==7.3.0
    pep8-naming==0.13.1
    flake8-builtins==3.0.0
    flake8-functions-names==0.4.0
    flake8-variables-names==0.0.6
