FASTQ_FILTERED_PREFIX = "filtered_"
FASTQ_EXTENSION = ".fastq"
FASTQ_TIMESTAMP_FORMAT = "%Y%m%d%H%M%S"

DEFAULT_GC_BOUNDS = (0, 100)
DEFAULT_LENGTH_BOUNDS = (0, 2**32)
DEFAULT_QUALITY_THRESHOLD = 0

BIOSEQ_STR_MAX_LEN = 60
BIOSEQ_STR_PREFIX_LEN = 57
BIOSEQ_STR_ELLIPSIS = "..."

AMINO_ACID_WATER_LOSS = 18.02

MSG_NO_FASTQ_PASSED = "No sequences passed the filter."
